spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: local_gukmo
    password: aclass
    driver-class-name: oracle.jdbc.driver.OracleDriver
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size : 1000
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

